##注解

In [ ]:
a=3  #單行註解
b=5
print(a+b)

8


In [ ]:
'''
多行註解
多行註解
多行註解
'''
a=3
b=5
print(a+b)

8


## 運算式

In [ ]:
#變數交換
x=1
y=10

z=x
x=y
y=z
print(x)
print(y)

10
1


In [ ]:
#python版本的變數交換
x=1
y=10
x,y = y,x
print(x)
print(y)

10
1


##變數平行設定

In [ ]:
x, y, z = 3, 4, 5
print(x)
print(y)
print(z)

3
4
5


## 資料型別
python屬於動態類型變數，使用前不需要宣告資料型態

In [ ]:
x=254
print(type(x))  #type(變數)用於檢查變數資料形態

y=254.0
print(type(y))

z='write'
print(type(z))

print(type(x==y))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>


##算數符號與順序

In [ ]:
x,y = 10,3
print(x/y)  #除法
print(x//y) #求商
print(x%y)  #求餘數

x,y,z = 3,4,5
x += 1  # x=x+1
y *= 2  # y=y*2
z **= 3  # z^3
print(x,y,z)

3.3333333333333335
3
1
4 8 125


In [ ]:
x = (5*(1+2)**2-3+4/2) #()括號 > **次方 > */乘除 > +-加減
print(x)

44.0


## 關係比較

In [ ]:
print(10==10)
x, y = 10, 20
print(x==y)      # == 關係比較
x=y          # =  指派值
print(x)

True
False
20


##型態轉換

In [ ]:
x="must"
print(10*x)
print("10"+x)
print(10,x)

mustmustmustmustmustmustmustmustmustmust
10must
10 must


In [ ]:
x = 12
print(type(x))
y = float(x)+0.5 #強制型別轉換
print(type(y))
print(int("123"))
print(int(123.33))
print(int(float("123.33")))

<class 'int'>
<class 'float'>
123
123
123


In [ ]:
print(eval("3+5"))       #eval會把str型態的表示式，轉換成數學式進行計算
id = input("請輸入產品編號：")
print(type(id))
print(type(eval(id)))

8
請輸入產品編號：12345
<class 'str'>
<class 'int'>


In [ ]:
r = eval(input("請輸入圓的半徑："))
area = r*r*3.14159
print("圓面積為：",area)

請輸入圓的半徑：10
圓面積為： 314.159


## print的三種方式
1. 透過,區隔要列印的變數

In [ ]:
print("This", "is", "a", "book")

This is a book


2. 利用字串的str.format() (新式)

In [ ]:
print("This {} a book".format("is"))

This is a book


3. %格式化输出字符串 (舊式)

In [ ]:
print("This %s a %s" % ("is", "book"))

This is a book


## 格式化輸出

---
%d = int , %f = float , %s = string

%5d = 固定5位數，不足則補空格

%-5d = 固定5位數，不足則補空格(補在後方)

%8.2f = 固定8字元以及2位小數(字元包括小數點)，不足則補空格

In [ ]:
price,temp = 23.8,"價格 = "
print("%10s %8.2f" %(temp, price))

     價格 =     23.80


In [ ]:
print(100, 200, 300, end=" X ")  # end 是結束字符，預設為\r\n
print(100, 200, 300, sep=" % ")  # sep 是間隔字符，預設為空格

100 200 300 X 100 % 200 % 300


##判定式
if...else

In [ ]:
a=3
b=4
if a <= b:
    print("b是比較大的數字")
else:
    print("a是比較大的數字")

b是比較大的數字


In [ ]:
grade=87
print("成績評鑑：")
if grade >= 90:
    print("優等")
elif grade >=80:
    print("甲等")
elif grade >=70:
    print("乙等")
elif grade >=60:
    print("丙等")
else:
    print("不及格")


成績評鑑：
甲等


##for迴圈 與 range

In [ ]:
list1 = list(range(5))
print(list1)

list2 = list(range(3,8,2))     #range(起始，中止，間隔) if(中止 > 起始) 間隔一定為正數
print(list2)

list3 = list(range(8,3,-1))    #range(起始，中止，間隔) if(起始 > 中止) 間隔一定為負數
print(list3)

[0, 1, 2, 3, 4]
[3, 5, 7]
[8, 7, 6, 5, 4]


In [ ]:
#for 變數 in 陣列 (陣列有多少東西就執行多少遍，每次執行將該陣列元素賦予變數)
list1 = ["A","B","C"]
for i in list1:
  print(i)

#以 range 產生陣列
for j in range(3,8,2):
  print(j,end='')

A
B
C
357

### 雞兔同籠，若共有35個頭，94隻腳，請問有幾隻雞?幾隻兔?

In [ ]:
for chicken in range(0,36):
    rabbit=35-chicken
    if (2*chicken+4*rabbit) == 94:
        print("雞有",chicken,"隻,兔子有",rabbit,"隻")
        break
else:
    print("無解")

雞有 23 隻,兔子有 12 隻


## while迴圈

In [ ]:
sum=0
count=1
while count <=10:
    sum += count
    count += 1
print("1+2+3+...+10=",sum)

1+2+3+...+10= 55


### 本金10000元，定存年利率0.6%，請問多久銀行存款會翻倍

In [ ]:
x=10000
years=0
while x <= 20000:
    x=x*1.006
    years += 1
print(str(years), "年以後，存款加倍，為", int(x),"元")

116 年以後，存款加倍，為 20015 元


##基本模組 - Random

In [ ]:
import random
print(random.randint(1,10))   #隨機產生n1(含)到n2(含)之間的整數
print(random.uniform(1,10))   #隨機產生n1到n2之間的浮點數
print(random.random())     #隨機產生一個0到1之間的浮點數

10
8.987915792577525
0.9029854380160454


In [ ]:
import random
list1 = [10,30,50,70,90,110,130,150,170,190,210,230,250,270,290]

for i in range(5):
  print(random.choice(list1))   #隨機從某陣列/元組中抽取值

290
150
250
210
90


##基本模組 - Math

In [ ]:
import math
print(math.pi)                      #π
print(math.pow(2,3))                   #次方
print(8.3*10.58*math.sin(37.0/180*math.pi)/2)      #sin
print(math.sqrt(25))                   #平方根

3.141592653589793
8.0
26.423892221536985
5.0


In [ ]:
import math
r=input("請輸入圓的半徑：")
area=float(r)*float(r)*math.pi
print("圓面積為：",area)

請輸入圓的半徑：10
圓面積為 314.1592653589793


# Python物件
## List[串列] Tuple(元組) Dictionary{字典} Sets{集合}

## List[串列]
使用中括號[]包裹元素

In [ ]:
expenses = [1138, 101, 12, 300, 2049]
print(expenses[0]) #索引從0開始
print(expenses[1]) #索引從1開始
print(expenses[-1]) #倒數第一個
print(expenses[-2]) #倒數第二個

1138
101
2049
300


In [ ]:
list1 = [1,2,3,4,5,3]

print(list1 * 2)                                #串列乘法

print("陣列中有元素 " + str(len(list1)) + " 個")              #計算串列元素數量

print("最大值：" + str(min(list1)),"最小值：" + str(max(list1)))       #尋找串列最大/最小數值

print("陣列中第四個元素為：" + str(list1.index(4+1)))             #尋找指定位置的數值

print("3在陣列中出現 " + str(list1.count(3)) + " 次")           #計算串列中指定值的出現次數

[1, 2, 3, 4, 5, 3, 1, 2, 3, 4, 5, 3]
陣列中有元素 6 個
最大值：1 最小值：5
陣列中第四個元素為：4
3在陣列中出現 2 次


In [ ]:
list2 = [1,2,3,4,5]

list2.insert(3,8)          #在指定位置加入值(n1 = 位置, n2 = 值)
print(list2, end="\r\n\r\n")

list2.remove(3)           #移除指定值(僅第一次出現)
print(list2, end="\r\n\r\n")

list2.append(6)           #從最後方加入新值
print(list2, end="\r\n\r\n")

L1 = list2.pop(0)         #抽出指定位置的值，n1預設為最後一個元素
print(list2)
print(L1, end="\r\n\r\n")

L2 = list2[0:3:2]         #尋找指定範圍的值，n1 = 起始, n2 = 終止, n3 = 間隔
print(list2)
print(L2)

[1, 2, 3, 8, 4, 5]

[1, 2, 8, 4, 5]

[1, 2, 8, 4, 5, 6]

[2, 8, 4, 5, 6]
1

[2, 8, 4, 5, 6]
[2, 4]


In [ ]:
list3 = [5,3,7,3,7,9,4,6,3,2]

list3.sort()             #從小到大排序
print(list3, end="\r\n\r\n")

list3.reverse()           #串列反轉
print(list3, end="\r\n\r\n")

print(max(list3), end="\r\n")    #找串列中最大值
print(min(list3), end="\r\n\r\n")  #找串列中最小值

list3.clear()            #清空串列
print(list3)

[2, 3, 3, 3, 4, 5, 6, 7, 7, 9]

[9, 7, 7, 6, 5, 4, 3, 3, 3, 2]

9
2

[]


## Tuple (元組)
tuple(元組)可視為不可改變的串列，tuple跟list很像，但是我們不能新增、刪除或更新tuple的元素。tuple的好處有：
1. 佔用較少空間
2. 可當作dictionary(字典)的鍵值
3. 可當作函式引數

In [ ]:
tuple1 = (1, "香蕉", True)  #可容納不同形態的元素
print(tuple1)

ListA = ['A','B','C']
TupleA = tuple(ListA)     #把List轉為Tuple
print(TupleA)
print(TupleA[1])

(1, '香蕉', True)
('A', 'B', 'C')
B


##字典
以大括號包覆

以{鍵-值}方式存儲資料

In [ ]:
dict1 = {"香蕉":20, "蘋果":50, "橘子":30}
print(dict1["蘋果"])                #字典只能以鍵作索引，不存在位置與順序

dict1["鳳梨"] = 80                #新增資料
print(dict1)

"蘋果" in dict1                  #檢查字典裏是否有特定值

50
{'香蕉': 20, '蘋果': 50, '橘子': 30, '鳳梨': 80}


True

In [ ]:
dict2 = {"香蕉":20, "蘋果":50, "橘子":30}

print(dict2.items())      #顯示字典所有的資料

print(dict2.keys())      #顯示字典所有的鍵

print(dict2.values())     #顯示字典所有的值

dict_items([('香蕉', 20), ('蘋果', 50), ('橘子', 30)])
dict_keys(['香蕉', '蘋果', '橘子'])
dict_values([20, 50, 30])


In [ ]:
dict3 = {"香蕉":20, "蘋果":50, "橘子":30}

listitem = dict3.items()
for fruit, price in listitem:
  print("%s 的售價為 %d 元" %(fruit,price))

香蕉 的售價為 20 元
蘋果 的售價為 50 元
橘子 的售價為 30 元


In [ ]:
dict3 = {"香蕉":20, "蘋果":50, "橘子":30}
print(dict3.get("香蕉"))        #檢查字典中有沒有相應的鍵。如有，回傳值
print(dict3.get("西瓜",99))      #如沒有則回傳預設值
print(dict3.get("西瓜"))        #如找不到鍵有沒有預設值，回傳"None"

dict3.setdefault("哈密瓜",120)     #用法與get相似，但如果找不到則會建立新資料
print(dict3)

20
99
None
{'香蕉': 20, '蘋果': 50, '橘子': 30, '哈密瓜': 120}


##自訂函數

In [ ]:
def sqarea(a,b=10):           #此函數要求兩個變數作處理。事先賦予變數為預設值，如果在呼叫函數時沒有給變數則用預設值
  ans = a * b
  print(ans, end="\r\n\r\n")

a = int(input())
sqarea(a)                # a(input) * b(預設)
b = int(input())
sqarea(a,b)               # a(input) * b(input)

5
50

20
100



In [ ]:
def plus(*data):          #彈性輸入法。"*"號代表輸入的資料會儲存在元組内，不限制資料輸入個數
  ans = 0
  print(type(data))
  for i in data:
    ans += i
  print(ans)

plus(1,2,3)
plus(1,2,3,4,5,6)
plus(1,2,3,4,5,6,7,8,9,10) 

<class 'tuple'>
6
<class 'tuple'>
21
<class 'tuple'>
55


##os套件：用來處理文件與目錄，與檔案相關操作

In [ ]:
import os
print(os.getcwd()) #顯示目前所在的工作目錄
os.listdir(".")  #顯示目錄下的檔案

/content


['.config', 'sample_data']

In [ ]:
os.makedirs("test")   #新增目錄
os.listdir(".")     #顯示目錄下的檔案

['.config', 'test', 'sample_data']

In [ ]:
os.rmdir("test")    #移除目錄
os.listdir(".")     #顯示目錄下的檔案

['.config', 'sample_data']

## 檔案處理
os套件有自己的檔案處理命令，而比較常用的是python內建的open
* w = 可寫(預設建立檔案) 若檔案存在則會清除舊檔案
* w+ = 可寫可讀(預設建立檔案) 若檔案存在則會清除舊檔案
* r = 可讀
* r+ = 可寫可讀 但寫入資料指向開頭
* a = 可寫不能讀 寫入資料指向尾端
* a+ = 可寫可讀 寫入資料指向尾端
* b = 轉為2進位文件
* ab+ = 2進位文件的讀寫 寫入資料指向尾端

In [ ]:
os.path.isfile("a.txt")       #檢查檔案是否存在

False

In [ ]:
a=open("a.txt","w")         #新增檔案
a.write("This is a test1")
a.write("This is a test2\n")
a.write("This is a test3\n")
a.close()              #關閉檔案

os.path.isfile("a.txt")       #檢查檔案是否存在

True

In [ ]:
a=open("a.txt","r")         #讀取檔案
print(a.readline())
print(a.readline())
print(a.readline())         #多餘的命令，檔案只有2行
a.close()

a=open("a.txt","r")
print(a.readlines())        # "readlines" 可一次讀取多行
a.close()

This is a test1This is a test2

This is a test3


['This is a test1This is a test2\n', 'This is a test3\n']


In [ ]:
a=open("a.txt", "a")       #附加檔案(附加於結尾)
a.write("This is test4\n")
a.close()

a=open("a.txt","r")
print(a.readlines())
a.close()

['This is a test1This is a test2\n', 'This is a test3\n', 'This is test4\n', 'This is test4\n']


In [ ]:
a=open("a.txt","r+")       #附加檔案(附加於開頭)
a.write("This is a test5\n")
a.close()

a=open("a.txt","r")
print(a.readlines())
a.close()

['This is a test5\n', 'his is a test2\n', 'This is a test3\n', 'This is test4\n', 'This is test4\n']


In [ ]:
if os.path.isfile("a.txt"):
    os.remove("a.txt")    #刪除檔案
    print("檔案刪除成功")
else:
    print("找不到檔案")
print(os.path.isfile("a.txt"))

檔案刪除成功
False


## numpy
* numpy由c撰寫，速度快python 10~1000倍以上
* numpy儲存結果較正確，python數字儲存不正確
* numpy節省記憶體儲存空間
* numpy的向量(矩陣計算)速度快
* numpy的取值方便

In [ ]:
a_list=[1,2,3,4,5]      #python 原版陣列（不可作陣列計算）
print(a_list*3)

import numpy as np
a=np.array([1,2,3,4,5])   #numpy 陣列（可作陣列計算）
print(a*3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 3  6  9 12 15]


In [ ]:
a=np.array([1,2,3,4,5])
print(type(a))
print(a.shape) #ndaary的形狀
print(a.dtype) #資料的型態
print(a.ndim) #維度

<class 'numpy.ndarray'>
(5,)
int64
1


##創造陣列

In [ ]:
print(np.empty((2,3,3),dtype=int))    #創造numpy陣列,内容皆爲無意義；用法為 numpy.empty((shape),dtype=datatype)

[[[           48688368        476741369971        489626271861]
  [       433791696995        498216206368        468151435365]
  [       476741369968        416611827826        450971566194]]

 [[       519691042924        502511173664        416611827822]
  [       416611827830        463856468073        420906795105]
  [       433791697004 6990476126585880576 7598246928484140988]]]


In [ ]:
print(np.zeros((2,2,3)))         #創造numpy陣列,内容皆爲0；用法為 numpy.zeros((shape),dtype=datatype)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
print(np.ones((2,2,3)))         #創造numpy陣列,内容皆爲1；用法為 numpy.ones((shape),dtype=datatype)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [ ]:
print(np.arange(2,10,2))        #創造numpy陣列；用法為 numpy.arange(開始點，結束點，跳數)

[2 4 6 8]


##讀取

In [2]:
import numpy as np
my_array=np.arange(10)
print(my_array)
print(my_array[0])      
print(my_array[0:5])      #讀取位置從零到五的資料

[0 1 2 3 4 5 6 7 8 9]
0
[0 1 2 3 4]


In [3]:
my_2d_array=np.array([np.arange(0,5),np.arange(5,10)])    #建立二維陣列
print(my_2d_array)
print(my_2d_array[1,:])   #讀取第一列資料
print(my_2d_array[:,1])   #讀取第一行資料
print(my_2d_array[1,1])   #讀取第一列，第一行資料

[[0 1 2 3 4]
 [5 6 7 8 9]]
[5 6 7 8 9]
[1 6]
6


In [6]:
my_array=np.arange(0,10)
print(my_array)
print(my_array.shape)   #讀取陣列形狀

print((np.arange(0,100).reshape(10,10)))  #建立大小為100的一維陣列，然後改爲大小為10，10的二維陣列

[0 1 2 3 4 5 6 7 8 9]
(10,)
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [7]:
b=np.array([56, 8, 19, 14, np.nan])  #放入空值
print(b)

[56.  8. 19. 14. nan]


## 錯誤處理

In [8]:
try:
  a = 1 + 1
except IOError:
  print("輸入/輸出錯誤")
except NameError:
  print("變數名稱錯誤")
except ValueError:
  print("數值錯誤")
except ZeroDivisionError:
  print("除數為零的錯誤")
except Exception as e:
  print("發生" + e + "錯誤")
else:
  print("沒有發生錯誤")
finally:
  print("程式執行完畢")

沒有發生錯誤
程式執行完畢
